### ISSUE TITLE
cannot find token.json

### ISSUE THREAD

**Issue by shahabali123** [gsuitedevs/python-samples#24]
Hi I tried the steps given on the link of google python quickstart. I created an account on google developer and created a project and enabled api for the project but I got an error token.json file not present. Any idea how I can get the token.json file? I get the credentials.json file when I download the client configuration files after enabling drive api but I don't get token.json file. Any help?

**Comment by erickoledadevrel** [comment]
Which quickstart specifically are you running? The token.json file should be created for you after you go through the OAuth flow.

**Comment by shahabali123** [comment]
Here's the link:
https://developers.google.com/drive/api/v3/quickstart/python

**Comment by shahabali123** [comment]
I just follow the steps given in this link directly. By OAuth flow you mean that step when you select a project to enable the drive api?

**Comment by shahabali123** [comment]
No it doesn't open a browser (I mean this step doesn't occur where I select an account and approve certain scopes), am using jupyter notebook with python 3.6.0.

**Comment by erickoledadevrel** [comment]
I'm not sure this code will run correctly in a Python notebook. Can you paste the exact output you see when running the quickstart?

**Comment by shahabali123** [comment]
c:\users\shahab ali\appdata\local\programs\python\python36\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
usage: ipykernel_launcher.py [--auth_host_name AUTH_HOST_NAME]
                             [--noauth_local_webserver]
                             [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                             [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\Shahab Ali\AppData\Roaming\jupyter\runtime\kernel-a30fb352-8814-4978-81ff-45062cd6be4a.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2


c:\users\shahab ali\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by shahabali123** [comment]
this is what I get as an output after running the code

**Comment by shahabali123** [comment]
Which IDE should I use to run this code successfully?

**Comment by erickoledadevrel** [comment]
You can run it locally on the command line if you have Python installed, or you can use our hosted Cloud Shell environment:

https://console.cloud.google.com/cloudshell/editor

When using Cloud Shell, add the command line parameter `--noauth_local_webserver` when executing the Python script to handle the callback correctly.

**Comment by dcada** [comment]
I think the problem is that you are using the wrong credential. You are using service account key and the correct one would be client IDs OAuth 2.0.

The Service account is like this:
{
  "type": "service_account",
  "project_id": "dcada06",
  "private_key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhAotQ==\n-----END PRIVATE KEY-----\n",
  "client_email": "teste2@dcada06.iam.gserviceaccount.com",
  "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/teste2%40dcada06.iam.gserviceaccount.com"
}

And the client IDs OAuth 2.0. is like this:
{"installed":{"client_id":"xxxxxxxxxxx-bgbnarn62prhaldem0upsoulmp8h1pac.apps.googleusercontent.com",
    "project_id":"dcada06",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
    "client_secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}

I had the same problem and was this

**Comment by shengyaliu1212** [comment]
@syedshahabali Hey did you solve the issue in the end? I'm encountering sth similar...
