### ISSUE TITLE
KeyError: '_module' error 

### ISSUE THREAD

**Issue by Naseem126** [gsuitedevs/python-samples#38]
I get the below error when running the script ::

PS C:\Users\nhr\Desktop\Gmail_Api> python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    main()
  File "quickstart.py", line 14, in main
    creds = store.get()
  File "C:\Python27\lib\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Python27\lib\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Python27\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

## Steps to Reproduce the Problem

I have followed the sames procedure described in https://developers.google.com/gmail/api/quickstart/python

1. Install Python , PIP and all related modules
2. Enabled GMAIL API and saved the credentials.json file in project directory
2. Installed Google Client Library
4. Copied and Saved the Quickstart.py file in project directory
5. Run the python command to run quickstart.py

These are the files in my project directory:

09/25/2018  07:45 AM    <DIR>          .
09/25/2018  07:45 AM    <DIR>          ..
09/25/2018  07:46 AM    <DIR>          .idea
09/09/2018  09:03 PM               431 client_secret.json
09/09/2018  08:42 PM               431 credentials.json
09/09/2018  08:33 PM             4,285 index.html
09/09/2018  08:40 PM             3,076 index.js
09/09/2018  08:56 PM             1,001 quickstart.py
09/09/2018  08:47 PM               340 token.json
               6 File(s)          9,564 bytes
              

## Specifications

- Python version (`python --version`) : 2.7
- OS (Mac/Linux/Windows) : Windows 10

**Comment by grant** [comment]
Can you fill out the steps to reproduce the problem?

**Comment by erickoledadevrel** [comment]
Do you already have a file in your working directory called `token.json`?

**Comment by HamidSayeed** [comment]
please answer this, new to this why do we require token.json ?

**Comment by Naseem126** [comment]
Hi, My apologies for late response. I have added the steps and other details to the description.

**Comment by erickoledadevrel** [comment]
The file `token.json` is created after you authorize access to your account. This error indicates that the file exists, but isn't in the expected format. What does your `token.json` file contain? Try renaming it to something else and running the quickstart again.

**Comment by Naseem126** [comment]
> The file `token.json` is created after you authorize access to your account. This error indicates that the file exists, but isn't in the expected format. What does your `token.json` file contain? Try renaming it to something else and running the quickstart again.

Thanks a lot. It worked fine after renaming token.json. now we have a new token.json in its place created by the script.

**Comment by Thomasster** [comment]
> The file `token.json` is created after you authorize access to your account. This error indicates that the file exists, but isn't in the expected format. What does your `token.json` file contain? Try renaming it to something else and running the quickstart again.

Worked well. Thanks a lot. :)

**Comment by erickoledadevrel** [comment]
In both of your cases, how did the original (non-working) `token.json` file get there? Did you create it? Did the folder already have one in there, from a quickstart run in another programming language?

**Comment by Naseem126** [comment]
I am not sure, but it looks like the token.json was created by the script
at the first run, which did not work.

**Comment by LucaCappelletti94** [comment]
Hi, how do I create a `token.json`? Is there an example?

**Comment by max326-coder** [comment]
Does anyone have solution for it or not



PS C:\Users\Dhaval\Downloads\uds-master> python3 uds.py push ~\Desktop\ffmpeg.exe
Traceback (most recent call last):
  File "uds.py", line 534, in <module>
    main()
  File "uds.py", line 452, in main
    uds = UDS()
  File "uds.py", line 46, in __init__
    self.api = GoogleAPI()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 19, in __init__
    self.reauth()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 25, in reauth
    credentials = store.get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by micjgam** [comment]
So... I just went through this rigamarole as well with GCP. In the end, I was able to generate the credentials.json file and the subsequent token.json.

However, now I am getting a KeyError: '_module' error when calling ezgmail.init(). I have the prerequisite modules and files already. All solutions say to delete the token.json file and rerun the authorization process, but this does not work.

Here is the traceback:

      File "<stdin>", line 1, in <module>
      File "c:\Installs\Python\lib\site-packages\ezgmail\__init__.py", line 471, in init
         creds = store.get()
      File "c:\Installs\Python\lib\site-packages\oauth2client\client.py", line 407, in get
         return self.locked_get()
      File "c:\Installs\Python\lib\site-packages\oauth2client\file.py", line 54, in locked_get
         credentials = client.Credentials.new_from_json(content)
      File "c:\Installs\Python\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
         module_name = data['_module']
     KeyError: '_module'

*** UPDATE ***

I changed a line in the ezgmail/init.py file (line 471) from:

      creds = store.get()
to:

     creds = None
Immediately upon running

     import ezgmail
apparently a new token.json file is written. I then reverted the ezgmail/init.py file (line 471) back to...

     creds = store.get()
... and now I can run ezgmail.init() with no issues!

This represents my limited knowledge of python and I am only just beginning, so please bear with my explanation above.  I aim to try and explain as best as I can how I found a solution so that someone can possibly walk away with an answer as to why a solution works rather than just "it works" and I can move on.

**Comment by wescpy** [comment]
The **root cause** for this error is that the current `token.json` (or `storage.json`) file you're using was written by an app using newer Python auth client libraries (meaning your code wrote the file with minimal content).

The `oauth2client` library is older and requires such a file (written by itself) include a `_module` entry in the JSON payload which doesn't exist. Sure, temporarily renaming `creds = None` works, but in reality, you can just blow away that token file and run your script again (and re-auth) without changing any of its code.

If you're confused by this and want to see examples like an old one using `oauth2client` and a new one using the replacement client libs where your code has to write the (abridged) token file that's incompatible with `oauth2client`, see both of the Drive samples I created at <https://github.com/wescpy/gsuite-apis-intro/tree/master/python>.
